# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Start Deployment!
      - name: decrypt
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
          --output $HOME/secrets/key google_compute_engine.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: test key
        run: ls $HOME/secrets/key
      - name: chmod
        run: chmod 600 $HOME/secrets/key
      - name: ssh
        run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key yi-chunsung@34.69.64.194 "cd github_actions_testing/;git pull"  
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Complete.
